database:
  type: sqlite
  sqlite:
    file: "kitffa.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "endiorite"
  worker-limit: 1

world:
  name: 'kitffa'
  #on join
  instantTp: false

#dans le word kitffa (zone protégée)
# permission pour bypass dans plugins.yml
# true : activé
# false : désactivé
kit-ffa-protections:
  damage: true
  hunger: true
  place: true
  break: true
  drop: true

combatlogger:
  combat-time: 10
  updatePlayerCombat: true
  killOnDisconnectCombat: true
  #permission pour bypass : kitffa.permissions.combatlogger.bypass
  banned-commands:
    - "tp"
    - "refill"
    - "warp"
    - "tpa"
    - "spawn"
    - "spawntp"
    - "hub"
    - "f"
    - "hubtp"
    - "spawntp"
    - "shop"
    - "lobby"
    - "lobbytp"
    - "rekit"

kit:
  cooldown:
    enabled: true
    time: 5

heal:
  potions:
    enabled: true
    # 3 cœurs
    heal: 6
    size:
      x: 4.125
      y: 2.125
      z: 4.125
      #4 blocs
      max: 16
  soup:
    item: "beetroot_soup"
    enabled: true
    # 2 cœurs
    heal: 4

kb:
  knockback: 0.354
  attackCooldown: 7

others:
  #Mettez 0 si vous ne voulez pas de cooldown
  ender-pearl-cooldown: 10
  chat-format: "{league} {player} : §f{message}"
  tag-format: "§o§e[§f{HEAL} §e/ §f{MAX}§e]"