database:
  type: sqlite
  sqlite:
    file: "kitffa.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "endiorite"
  worker-limit: 1

world:
  name: 'kitffa'
  #on join
  instantTp: false

combatlogger:
  combat-time: 10
  updatePlayerCombat: true
  killOnDisconnectCombat: true
  #permission pour bypass : kitffa.permissions.combatlogger.bypass
  banned-commands:
    - "tp"
    - "refill"
    - "warp"
    - "tpa"
    - "spawn"
    - "spawntp"
    - "hub"
    - "f"
    - "hubtp"
    - "spawntp"
    - "shop"
    - "lobby"
    - "lobbytp"
    - "rekit"