database:
  type: sqlite
  sqlite:
    file: "kitffa.sqlite"
  mysql:
    host: localhost
    username: root
    password: ""
    schema: "endiorite"
  worker-limit: 1

world:
  name: 'kitffa'
  #on join
  instantTp: false

#dans le word kitffa (zone protégée)
# permission pour bypass dans plugins.yml
# true : activé
# false : désactivé
kit-ffa-protections:
  damage: true
  hunger: true
  place: true
  break: true

combatlogger:
  combat-time: 10
  updatePlayerCombat: true
  killOnDisconnectCombat: true
  #permission pour bypass : kitffa.permissions.combatlogger.bypass
  banned-commands:
    - "tp"
    - "refill"
    - "warp"
    - "tpa"
    - "spawn"
    - "spawntp"
    - "hub"
    - "f"
    - "hubtp"
    - "spawntp"
    - "shop"
    - "lobby"
    - "lobbytp"
    - "rekit"

kit:
  cooldown:
    enabled: true
    time: 5